version: "3.9"
services:
  WebClient:
    image: 'karlaru/tcw'
    ports:
      - "8080:8080"
    environment:
      - LONDON_URL=http://london/api/v1/tire-change-times
      - MANCHESTER_URL=http://manchester/api/v2/tire-change-times
    links:
      - london
      - manchester
  london:
    image: 'surmus/london-tire-workshop:2.0.0'
    ports:
      - "9003:80"
  manchester:
    image: 'surmus/manchester-tire-workshop:2.0.0'
    ports:
      - "9004:80"